api:
  host: https://api.tmb.cat
  path: /v1/planner
  port: 443
  appId: e32e32aa
  appKey: c4ed3d248d10633182d9e7db6f585af1
# Add suggested locations to be shown as options in the form view.
# locations:
#   - id: 'airport'
#     icon: 'plane'
#     name: 'Portland International Airport (PDX)'
#     lat: 45.587579
#     lon: -122.593084
#   - id: 'zoo'
#     icon: building
#     lat: 45.51010444232195
#     lon: -122.71607145667079
#     name: Oregon Zoo, Portland, OR

### The persistence setting is used to enable the storage of places (home, work),
### recent searches/places, user overrides, and favorite stops.
### Pick the strategy that best suits your needs.
###
### If you do not require remote storage of preferences,
### then use the localStorage strategy outlined below (which is used by default).
### The localStorage strategy will use the browser application storage.
### It must be enabled to show the stored locations (see above).
persistence:
  enabled: true
  strategy: localStorage

### If using the OTP Middleware to store user profiles
### with Auth0 as the authentication mechanism,
### then use the otp_middleware strategy below instead: 
# persistence:
#  enabled: true
#  strategy: otp_middleware
#  auth0:
#    domain: your-auth0-domain
#    clientId: your-auth0-client-id
#  otp_middleware:
#    apiBaseUrl: https://otp-middleware.example.com
#    apiKey: your-middleware-api-key

map:
  initLat: 41.38266
  initLon: 2.17702
  baseLayers:
    - name: Dark
      url: https://api.tmb.cat/v1/maps/vts/xyz/tmb-dark/{z}/{x}/{y}.png?app_id=973e72fb&app_key=8db3e7a5812cf26582184a256c57a23b
      subdomains: 'abcd'
      attribution: ''
      maxZoom: 20
      hasRetinaSupport: true
    - name: Basic
      url: https://api.tmb.cat/v1/maps/vts/xyz/tmb-basic/{z}/{x}/{y}.png?app_id=973e72fb&app_key=8db3e7a5812cf26582184a256c57a23b
      attribution: ''

# it is possible to leave out a geocoder config entirely. In that case only
# GPS coordinates will be used when finding the origin/destination.

# example config for a Pelias geocoder (https://pelias.io/)
#geocoder:
#  apiKey: MAPZEN_KEY
#  boundary:
#    rect:
#      minLon: -123.2034
#      maxLon: -122.135
#      minLat: 45.273
#      maxLat: 45.7445
#  focusPoint:
#    lat: 45.5223452
#    lon: -122.6821804
#  # Custom fetch options to pass to geocoder resource.
#  # options:
#  #   headers:
#  #     x-custom-header: abc123
#  # required geocoder type.
#  type: PELIAS
#  # This base URL is required as the libraries will default to using now-defunct
#  # mapzen urls
#  baseUrl: https://geocoder.example.com/pelias/v1

# example config for an ArcGIS geocoder
# (https://developers.arcgis.com/rest/geocode/api-reference/overview-world-geocoding-service.htm)
# WARNING: using the ArcGIS geocoder with a persistence strategy of
#   `localStorage` will result in an error being thrown because ArcGIS
#   requires the use of a paid account to store geocode results.
#   See https://developers.arcgis.com/rest/geocode/api-reference/geocoding-free-vs-paid.htm
# geocoder:
#   boundary:
#     rect:
#       minLon: -123.2034
#       maxLon: -122.135
#       minLat: 45.273
#       maxLat: 45.7445
#   focusPoint:
#     lat: 45.5223452
#     lon: -122.6821804
#   # required geocoder type.
#   type: ARCGIS

# Use this mode config for the enhanced Transit+ config
modes:
  transitModes:
    - mode: TRANSIT,WALK
      label: transit + walk

  accessModes:
    - mode: BICYCLE
      label: Transit + Bike

  bicycleModes:
    - mode: BICYCLE
      label: Own Bike
      iconWidth: 18


routingTypes:
  - key: ITINERARY
    text: Exact Time

### Use this config for the standard mode selector
# modeGroups:
#   - name: Transit
#     modes:
#       - TRAM
#       - BUS
#   - name: Walk/Bike
#     modes:
#       - WALK
#       - BICYCLE
